// app/layout.tsx
import { Metadata } from "next"
import { Suspense } from "react"
import Providers from "./_providers"
import "./globals.css"
// import Header from "@/components/header";

export const metadata: Metadata = {
    title: "Test",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className="bg-gray-100">
                <Suspense>
                    <Providers>{children}</Providers>
                </Suspense>
            </body>
        </html>
    )
}
