// app/layout.tsx
import { Metadata } from "next";
import "./globals.css";
import Providers from "./_providers";
// import Header from "@/components/header";

export const metadata: Metadata = {
    title: "Test",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <body  className="bg-gray-100">
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
